<script setup lang="ts">
import { Link, router, useForm } from '@inertiajs/vue3';
import { computed, onMounted, onUnmounted, ref } from 'vue';
import AdminLayout from '@/Layouts/AdminLayout.vue';
import PageMeta from '@/Components/PageMeta.vue';
import StatusBadge from '@/Components/StatusBadge.vue';
import { hondurasDateTime } from '@/Composables/hondurasDate';
import type { Doctor, ExtractionCandidate, MedicalDocument, Patient } from '@/types';

type RevisionChange = { field: string; before: unknown; after: unknown };
type Revision = { id: string; number: number; status: string; current: boolean; reason: string | null; actor: string | null; created_at: string | null; sha256: string | null; changes: RevisionChange[] };
type RelatedInvoice = { id: string; status: string; ncf: string | null; issued_at: string | null; download_url: string | null };
const props = defineProps<{ document:MedicalDocument; doctors:Doctor[]; patients:Patient[]; revisionHistory:Revision[]; relatedInvoices:RelatedInvoice[]; hasIssuedInvoice:boolean; canCorrect:boolean; canCreateInvoice:boolean }>();
const allowlist = ['patient_name','patient_document','birth_date','age','age_at_consultation','sex','issue_date','consultation_date','consultation_time','start_date','end_date','leave_start_date','leave_end_date','days','leave_days','symptoms','medical_reason','diagnosis','treatment','recommendations','observations','doctor_name','doctor_credential','clinic_name','clinic_address'] as const;
const labels:Record<string,string> = { patient_name:'Paciente',patient_document:'Documento del paciente',birth_date:'Fecha de nacimiento',age:'Edad',age_at_consultation:'Edad en consulta',sex:'Sexo',issue_date:'Fecha de emisión',consultation_date:'Fecha de consulta',consultation_time:'Hora de consulta',start_date:'Fecha inicial',end_date:'Fecha final',leave_start_date:'Inicio del descanso',leave_end_date:'Fin del descanso',days:'Días',leave_days:'Días de descanso',symptoms:'Síntomas',medical_reason:'Motivo médico',diagnosis:'Diagnóstico',treatment:'Tratamiento',recommendations:'Recomendaciones',observations:'Observaciones',doctor_name:'Profesional',doctor_credential:'Credencial profesional',clinic_name:'Clínica',clinic_address:'Dirección de clínica' };
const correctionCategories = ['Datos del paciente','Fecha o duración','Diagnóstico o motivo médico','Tratamiento o recomendaciones','Error de transcripción','Otro'];
const raw = props.document.extractions?.[0]?.candidates ?? {};
const grouped:Record<string,unknown[]> = Object.fromEntries(allowlist.map(field => [field,[]]));
if (Array.isArray(raw)) for (const candidate of raw as ExtractionCandidate[]) { if (candidate?.field && candidate.field in grouped) grouped[candidate.field].push(candidate); }
else for (const [field,candidate] of Object.entries(raw)) { if (field in grouped) grouped[field].push(...(Array.isArray(candidate) ? candidate : [candidate])); }
const value = (candidate:unknown) => { if (candidate == null) return ''; if (typeof candidate === 'object') { const item=candidate as Record<string,unknown>; return String(item.value ?? item.text ?? item.content ?? ''); } return String(candidate); };
const displayValue = (item:unknown) => item == null || item === '' ? 'Sin valor' : typeof item === 'object' ? JSON.stringify(item) : String(item);
const formatDate = (date:string|null) => hondurasDateTime(date);
const fields = allowlist.filter(field => grouped[field].length || Object.prototype.hasOwnProperty.call(props.document.confirmed_fields ?? {},field));
const seed = Object.fromEntries(fields.map(field => [field,props.document.confirmed_fields?.[field] ?? value(grouped[field][0])]));
const form = useForm({fields:seed as Record<string,string|null>,doctor_id:props.document.doctor?.id ?? '',patient_id:props.document.patient?.id ?? '',approve:false});
const correction = useForm({reason:''});
const correctionCategory=ref(''); const correctionObservation=ref(''); const showCorrection=ref(false); const openRevision=ref<string|null>(props.revisionHistory.at(-1)?.id ?? null);
const canMutate=computed(() => ['REVIEW_REQUIRED','READY'].includes(props.document.status)); const canIssue=computed(() => props.document.status === 'READY');
const save=(approve:boolean) => { if (!canMutate.value) return; form.approve=approve; form.put(route('admin.documents.confirm',props.document.id),{preserveScroll:true}); };
const submitCorrection=() => { correction.clearErrors(); if (!correctionCategory.value) return correction.setError('reason','Seleccione una categoría.'); if (correctionObservation.value.trim().length < 3) return correction.setError('reason','Describa la corrección en la observación.'); correction.reason=`${correctionCategory.value}: ${correctionObservation.value.trim()}`; correction.post(route('admin.documents.corrections.store',props.document.id),{preserveScroll:true}); };
const confirmAction=ref<'issue'|null>(null); const issue=() => router.post(route('admin.documents.issue',props.document.id),{},{preserveScroll:true,onSuccess:() => confirmAction.value=null});
let poll:number|undefined; onMounted(() => { if (props.document.status === 'PROCESSING') poll=window.setInterval(() => router.reload({only:['document']}),2000); }); onUnmounted(() => window.clearInterval(poll));
</script>

<template>
<AdminLayout :title="`Revisión · ${document.public_code || document.original_filename}`" eyebrow="Documentos / Revisión"><PageMeta title="Revisar documento" noindex/><section class="admin-content review-content">
<div class="workflow-scroll"><div class="workflow"><div class="done"><i>1</i><span>Carga</span></div><b></b><div :class="{done:document.status!=='PROCESSING'}"><i>2</i><span>Extracción</span></div><b></b><div :class="{active:['REVIEW_REQUIRED','READY'].includes(document.status),done:['READY','ISSUED','REVOKED','REPLACED'].includes(document.status)}"><i>3</i><span>Validación</span></div><b></b><div :class="{done:['READY','ISSUED','REVOKED','REPLACED'].includes(document.status)}"><i>4</i><span>Aprobación</span></div><b></b><div :class="{done:['ISSUED','REVOKED','REPLACED'].includes(document.status)}"><i>5</i><span>Emisión</span></div></div></div>
<div class="review-top"><div><StatusBadge :status="document.status"/><p>Archivo original: <strong class="code-wrap">{{ document.original_filename }}</strong></p></div><div class="action-row"><a class="button button--outline-small" :href="route('admin.documents.download',{document:document.id,version:'original'})">Descargar original</a><a v-if="document.issued_at" class="button button--outline-small" :href="route('admin.documents.download',{document:document.id,version:'issued'})">Descargar emitido</a><Link v-if="canCreateInvoice" class="button button--outline-small" :href="route('admin.invoices.create',{medical_document_id:document.id})">Generar factura</Link><button v-if="canCorrect" class="button button--outline-small" type="button" @click="showCorrection=!showCorrection">Crear corrección</button><button v-if="canIssue" class="button button--admin" type="button" @click="confirmAction='issue'">Emitir documento</button></div></div>
<div v-if="document.status==='PROCESSING'" class="panel process-state" role="status"><h2>Procesando documento</h2><p>La extracción se actualiza automáticamente. No hay mutaciones disponibles hasta que termine.</p></div>
<div v-if="document.status==='FAILED'" class="warning-box"><strong>El procesamiento falló</strong><p class="code-wrap">{{ document.processing_metadata?.error || 'El servidor no proporcionó un detalle público.' }}</p><Link class="button button--outline-small" :href="route('admin.documents.index')">Volver a documentos</Link></div>
<div v-if="hasIssuedInvoice" class="warning-box" role="alert"><strong>Este documento tiene una factura emitida relacionada</strong><p>La corrección del documento médico no modifica ni anula la factura fiscal. Revise la factura relacionada antes de continuar.</p><div v-for="invoice in relatedInvoices.filter(item => item.status==='ISSUED')" :key="invoice.id" class="action-row"><Link class="row-action" :href="route('admin.invoices.show',invoice.id)">Ver factura {{ invoice.ncf || 'emitida' }}</Link><a v-if="invoice.download_url" class="row-action" :href="invoice.download_url">Descargar factura PDF</a></div></div>

<form v-if="showCorrection && canCorrect" class="panel correction-panel" @submit.prevent="submitCorrection"><div class="panel-head"><div><p class="kicker">Nueva revisión</p><h2>Motivo de la corrección</h2><p>La categoría y la observación quedarán registradas en el historial.</p></div></div><div class="form-grid"><div class="field"><label for="correction-category">Categoría</label><select id="correction-category" v-model="correctionCategory" required><option value="" disabled>Seleccione una categoría</option><option v-for="category in correctionCategories" :key="category" :value="category">{{ category }}</option></select></div><div class="field field--wide"><label for="correction-observation">Observación</label><textarea id="correction-observation" v-model="correctionObservation" rows="3" maxlength="1900" required placeholder="Detalle qué dato debe corregirse y por qué."></textarea></div></div><span v-if="correction.errors.reason" class="field-error">{{ correction.errors.reason }}</span><div class="action-row"><button class="button button--admin" type="submit" :disabled="correction.processing">{{ correction.processing?'Creando...':'Crear revisión para corregir' }}</button><button class="button button--outline-small" type="button" @click="showCorrection=false">Cancelar</button></div></form>

<div v-if="canMutate" class="review-grid"><form class="panel form-panel" @submit.prevent="save(false)"><div class="panel-head"><div><p class="kicker">Datos extraídos</p><h2>Validación del documento</h2><p>Confirme o corrija los valores antes de aprobar.</p></div></div><div class="form-grid"><div class="field"><label for="patient">Paciente</label><select id="patient" v-model="form.patient_id"><option value="">Sin asociar</option><option v-for="patient in patients" :key="patient.id" :value="patient.id">{{ patient.first_name }} {{ patient.last_name }}</option></select><span v-if="form.errors.patient_id" class="field-error">{{ form.errors.patient_id }}</span></div><div class="field"><label>Profesional</label><select v-model="form.doctor_id" disabled><option v-for="doctor in doctors" :key="doctor.id" :value="doctor.id">{{ doctor.first_name }} {{ doctor.last_name }}</option></select></div><div v-for="field in fields" :key="field" class="field" :class="{'field--wide':['symptoms','medical_reason','diagnosis','treatment','recommendations','observations'].includes(field)}"><label :for="field">{{ labels[field] || field }}</label><textarea v-if="['symptoms','medical_reason','diagnosis','treatment','recommendations','observations'].includes(field)" :id="field" v-model="form.fields[field]" rows="3"></textarea><input v-else :id="field" v-model="form.fields[field]"><span v-if="form.errors[`fields.${field}`]" class="field-error">{{ form.errors[`fields.${field}`] }}</span></div></div><div class="action-row"><button class="button button--outline-small" type="submit" :disabled="form.processing">Guardar revisión</button><button class="button button--admin" type="button" :disabled="form.processing" @click="save(true)">Aprobar datos</button></div></form><aside class="review-aside"><div v-if="document.inconsistencies?.length" class="warning-box"><strong>Observaciones de consistencia</strong><p v-for="(issue,index) in document.inconsistencies" :key="index" class="code-wrap">{{ displayValue(issue) }}</p></div><div class="panel"><p class="kicker">Extracción</p><h3>Control humano requerido</h3><p>Compare los valores con el PDF original. La aprobación queda registrada en auditoría.</p></div><Link class="back-admin" :href="route('admin.documents.index')">← Volver a documentos</Link></aside></div>

<section v-if="revisionHistory.length" class="panel revision-history"><div class="panel-head"><div><p class="kicker">Trazabilidad</p><h2>Historial de revisiones</h2><p>Consulte el responsable, motivo, huella y campos modificados de cada versión.</p></div></div><article v-for="revision in revisionHistory" :key="revision.id" class="revision-item"><button class="revision-item__summary" type="button" :aria-expanded="openRevision===revision.id" @click="openRevision=openRevision===revision.id?null:revision.id"><span><strong>Revisión {{ revision.number }}</strong><StatusBadge :status="revision.status"/><small v-if="revision.current">Versión actual</small></span><span>{{ revision.actor || 'Actor no disponible' }} · {{ formatDate(revision.created_at) }}</span></button><div v-if="openRevision===revision.id" class="revision-item__detail"><dl><div><dt>Motivo</dt><dd>{{ revision.reason || (revision.number===1?'Emisión original':'Sin motivo registrado') }}</dd></div><div><dt>SHA-256</dt><dd class="code-wrap"><code>{{ revision.sha256 || 'No disponible' }}</code></dd></div></dl><div v-if="revision.changes.length" class="revision-comparison"><h3>Campos modificados</h3><div class="table-scroll"><table><thead><tr><th>Campo</th><th>Valor anterior</th><th>Valor corregido</th></tr></thead><tbody><tr v-for="change in revision.changes" :key="change.field"><th>{{ labels[change.field] || change.field }}</th><td>{{ displayValue(change.before) }}</td><td>{{ displayValue(change.after) }}</td></tr></tbody></table></div></div><p v-else class="revision-empty">No hay cambios de campos para comparar en esta revisión.</p><Link class="row-action" :href="route('admin.documents.review',revision.id)">Abrir esta revisión</Link></div></article></section>
</section><div v-if="confirmAction==='issue'" class="confirm-overlay" role="dialog" aria-modal="true" aria-labelledby="issue-title"><div class="panel confirm-panel"><h2 id="issue-title">Emitir documento</h2><p>Confirme que los datos son correctos. La versión emitida será inmutable.</p><div class="action-row"><button class="button button--outline-small" type="button" @click="confirmAction=null">Cancelar</button><button class="button button--admin" type="button" @click="issue">Confirmar emisión</button></div></div></div></AdminLayout>
</template>
