<script setup lang="ts">
import axios from 'axios';
import { Head, Link, router } from '@inertiajs/vue3';
import { computed, reactive, ref } from 'vue';
import AdminLayout from '@/Layouts/AdminLayout.vue';
import PageMeta from '@/Components/PageMeta.vue';

type Item = { service_code:string; description:string; quantity:number; unit_price:number; discount:number; tax_category:string };
type Patient = { id:string; first_name:string; last_name:string; document_number:string|null };
type MedicalDocument = { id:string; clinic_id:string; patient_id:string|null; public_code:string; consultation_date:string|null; consultation_time:string|null; patient?:Patient|null };
type BillingService = { id:string; code:string; name:string; default_price:string; tax_type:string };
const props = defineProps<{ clinics:Array<{id:string;name:string}>; patients:Patient[]; documents:MedicalDocument[]; sourceDocumentId:string; draftInvoice:any|null; services:BillingService[] }>();
const draft = props.draftInvoice;
const form = reactive({ clinic_id:draft?.clinic_id||props.clinics[0]?.id||'', patient_id:draft?.patient_id||'', medical_document_id:draft?.medical_document_id||props.sourceDocumentId||'', recipient_name:draft?.recipient_name||'', recipient_tax_id:draft?.recipient_tax_id||'', service_date:draft?.service_date||'', service_time:draft?.service_time||'', payment_method:draft?.payment_method||'EFECTIVO', paid_total:draft?.paid_total === null || draft?.paid_total === undefined ? null : Number(draft.paid_total), items:(draft?.items?.map((item:Item)=>({service_code:item.service_code||'',description:item.description,quantity:Number(item.quantity),unit_price:Number(item.unit_price),discount:Number(item.discount),tax_category:item.tax_category}))||[{service_code:'',description:'',quantity:1,unit_price:0,discount:0,tax_category:'EXENTO'}]) as Item[] });
const errors=ref<Record<string,string>>({}); const submitting=ref(false);
const lineNet=(item:Item)=>Math.max(0,item.quantity*item.unit_price-item.discount);
const totals=computed(()=>form.items.reduce((value,item)=>{const net=lineNet(item);const rate=item.tax_category==='GRAVADO_15'?.15:item.tax_category==='GRAVADO_18'?.18:0;value.subtotal+=item.quantity*item.unit_price;value.discount+=item.discount;value[item.tax_category==='EXENTO'?'exempt':item.tax_category==='EXONERADO'?'exonerated':item.tax_category==='GRAVADO_15'?'taxable15':'taxable18']+=net;value.tax+=net*rate;value.total+=net*(1+rate);return value},{subtotal:0,discount:0,exempt:0,exonerated:0,taxable15:0,taxable18:0,tax:0,total:0}));
const money=(value:number)=>new Intl.NumberFormat('es-HN',{style:'currency',currency:'HNL'}).format(value);
const serviceDate=(value?:string|null)=>value?new Intl.DateTimeFormat('es-HN',{dateStyle:'long',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`)):'No registrada';
const serviceTime=(value?:string|null)=>{if(!value)return 'No registrada';const [hours,minutes]=value.split(':').map(Number);return `${hours%12||12}:${String(minutes).padStart(2,'0')} ${hours<12?'a. m.':'p. m.'}`;};
const addItem=()=>form.items.push({service_code:'',description:'',quantity:1,unit_price:0,discount:0,tax_category:'EXENTO'});
const removeItem=(index:number)=>form.items.length>1&&form.items.splice(index,1);
const selectPatient=()=>{const patient=props.patients.find(item=>item.id===form.patient_id);if(!patient)return;form.recipient_name=`${patient.first_name} ${patient.last_name}`;form.recipient_tax_id=patient.document_number||'';};
const selectDocument=()=>{const document=props.documents.find(item=>item.id===form.medical_document_id);if(!document)return;form.clinic_id=document.clinic_id;form.patient_id=document.patient_id||'';form.recipient_name=document.patient?`${document.patient.first_name} ${document.patient.last_name}`:'';form.recipient_tax_id=document.patient?.document_number||'';};
const selectService=(item:Item)=>{const service=props.services.find(option=>option.code===item.service_code);if(!service)return;item.description=service.name;item.unit_price=Number(service.default_price);item.tax_category=service.tax_type;};
if(form.medical_document_id)selectDocument();
const submit=async()=>{errors.value={};submitting.value=true;try{const {data}=draft?await axios.put(route('admin.invoices.update',draft.id),form):await axios.post(route('admin.invoices.store'),form);router.visit(route('admin.invoices.show',data.id));}catch(error:any){errors.value=error.response?.data?.errors||{form:error.response?.data?.message||'No se pudo guardar el borrador.'};}finally{submitting.value=false;}};
</script>

<template>
  <Head :title="draft ? 'Editar factura' : 'Nueva factura'"/><AdminLayout :title="draft ? 'Editar factura' : 'Nueva factura'" eyebrow="Operación fiscal"><PageMeta :title="draft ? 'Editar factura' : 'Nueva factura'" noindex/>
    <section class="admin-content invoice-create"><div class="content-toolbar"><div><p class="kicker">Borrador fiscal</p><h2>{{ draft ? 'Editar borrador' : 'Registrar factura' }}</h2><p>Guardar no consume NCF. Los totales se recalculan en el servidor.</p></div><Link class="row-action" :href="route('admin.invoices.index')">Volver al listado</Link></div>
      <form class="panel form-panel" @submit.prevent="submit"><p v-if="errors.form" class="field-error">{{ errors.form }}</p>
        <div v-if="form.medical_document_id" class="invoice-source-card"><p class="kicker">Documento médico relacionado</p><h3>{{ props.documents.find(item=>item.id===form.medical_document_id)?.public_code }}</h3><dl><div><dt>Paciente vinculado</dt><dd>{{ form.recipient_name || 'No registrado' }}</dd></div><div><dt>Fecha de atención/servicio</dt><dd>{{ serviceDate(props.documents.find(item=>item.id===form.medical_document_id)?.consultation_date) }}</dd></div><div><dt>Hora de atención</dt><dd>{{ serviceTime(props.documents.find(item=>item.id===form.medical_document_id)?.consultation_time) }}</dd></div></dl><p>La clínica, el paciente y los datos del receptor se toman del documento vinculado.</p></div>
        <div class="form-grid"><div v-if="!form.medical_document_id" class="field"><label>Clínica</label><select v-model="form.clinic_id" required><option v-for="clinic in clinics" :key="clinic.id" :value="clinic.id">{{ clinic.name }}</option></select></div><div v-if="!form.medical_document_id" class="field"><label>Documento médico relacionado</label><select v-model="form.medical_document_id" @change="selectDocument"><option value="">Sin documento</option><option v-for="document in documents" :key="document.id" :value="document.id">{{ document.public_code }}</option></select></div><div v-if="!form.medical_document_id" class="field"><label>Paciente</label><select v-model="form.patient_id" @change="selectPatient"><option value="">No asociar</option><option v-for="patient in patients" :key="patient.id" :value="patient.id">{{ patient.first_name }} {{ patient.last_name }}</option></select></div><div v-if="!form.medical_document_id" class="field"><label>Cliente</label><input v-model="form.recipient_name" maxlength="255"></div><div v-if="!form.medical_document_id" class="field"><label>Fecha de atención/servicio</label><input v-model="form.service_date" type="date"></div><div v-if="!form.medical_document_id" class="field"><label>Hora de atención</label><input v-model="form.service_time" type="time"></div><div class="field"><label>Forma de pago</label><select v-model="form.payment_method"><option v-for="method in ['EFECTIVO','TARJETA','TRANSFERENCIA','MIXTO','OTRO']" :key="method">{{ method }}</option></select></div></div>
        <details class="invoice-advanced"><summary>Datos avanzados de cobro</summary><div class="form-grid"><div v-if="!form.medical_document_id" class="field"><label>Identidad / RTN</label><input v-model="form.recipient_tax_id" maxlength="100"></div><div class="field"><label>Monto pagado</label><input v-model.number="form.paid_total" type="number" min="0" step="0.01"></div></div></details>
        <div class="invoice-lines"><div class="invoice-lines__head"><h3>Servicios</h3><button class="row-action" type="button" @click="addItem">+ Agregar línea</button></div><div class="invoice-line-labels" aria-hidden="true"><span>Servicio</span><span>Descripción</span><span>Cant.</span><span>Precio</span><span>Total</span><span></span></div><div v-for="(item,index) in form.items" :key="index" class="invoice-line"><select v-model="item.service_code" aria-label="Servicio del catálogo" @change="selectService(item)"><option value="">Personalizado</option><option v-for="service in services" :key="service.id" :value="service.code">{{ service.name }}</option></select><input v-model="item.description" required maxlength="255" placeholder="Descripción manual"><input v-model.number="item.quantity" required type="number" min="0.001" step="0.001" aria-label="Cantidad"><input v-model.number="item.unit_price" required type="number" min="0" step="0.01" aria-label="Precio"><strong>{{ money(lineNet(item)*(item.tax_category==='GRAVADO_15'?1.15:item.tax_category==='GRAVADO_18'?1.18:1)) }}</strong><button class="row-action" type="button" @click="removeItem(index)">Quitar</button><details class="invoice-line__advanced"><summary>Impuestos, descuento y código manual</summary><div><label>Código<input v-model="item.service_code" maxlength="60"></label><label>Descuento<input v-model.number="item.discount" type="number" min="0" step="0.01"></label><label>Tipo fiscal<select v-model="item.tax_category"><option v-for="tax in ['EXENTO','EXONERADO','GRAVADO_15','GRAVADO_18']" :key="tax">{{ tax }}</option></select></label></div></details></div></div>
        <div class="invoice-preview"><h3>Resumen</h3><dl class="invoice-summary"><div><dt>Subtotal</dt><dd>{{ money(totals.subtotal) }}</dd></div><div><dt>Descuentos</dt><dd>{{ money(totals.discount) }}</dd></div><div><dt>Exento</dt><dd>{{ money(totals.exempt) }}</dd></div><div><dt>Exonerado</dt><dd>{{ money(totals.exonerated) }}</dd></div><div><dt>Gravado 15%</dt><dd>{{ money(totals.taxable15) }}</dd></div><div><dt>Gravado 18%</dt><dd>{{ money(totals.taxable18) }}</dd></div><div><dt>ISV</dt><dd>{{ money(totals.tax) }}</dd></div><div><dt>Total</dt><dd><strong>{{ money(totals.total) }}</strong></dd></div><div><dt>Saldo</dt><dd>{{ money(Math.max(0,totals.total-(form.paid_total ?? totals.total))) }}</dd></div></dl></div>
        <div class="action-row"><button class="button button--admin" type="submit" :disabled="submitting">{{ submitting ? 'Guardando...' : draft ? 'Guardar cambios' : 'Guardar borrador' }}</button></div>
      </form>
    </section>
  </AdminLayout>
</template>
