<script setup lang="ts">
import { Link, usePage } from '@inertiajs/vue3';
import AdminLayout from '@/Layouts/AdminLayout.vue';
import PageMeta from '@/Components/PageMeta.vue';
import StatusBadge from '@/Components/StatusBadge.vue';
import { hondurasDateTime } from '@/Composables/hondurasDate';
import type { MedicalDocument } from '@/types';

defineProps<{ counts: { documents: number; documents_today: number; pending_review: number; generated: number; certificates: number; incapacities: number; verifications: number; doctors: number; patients: number; specialties: number; active_clinics: number }; recent: MedicalDocument[] }>();
const date = (value: string) => hondurasDateTime(value);
const buildId = usePage().props.build_id as string;
</script>

<template>
    <AdminLayout title="Centro de operaciones" eyebrow="Panel administrativo">
        <PageMeta title="Panel administrativo" noindex />
        <section class="admin-content admin-dashboard">
            <div class="dashboard-hero"><div><p>Buenos días</p><h2>Todo lo importante, en un solo lugar.</h2><span>Revisa pendientes, crea documentos y accede rápidamente a los expedientes.</span></div><div class="dashboard-hero__actions"><Link class="button button--light" :href="route('admin.documents.generate', 'constancia')">+ Nueva constancia</Link><Link class="button dashboard-hero__secondary" :href="route('admin.patients.create')">Nuevo paciente</Link></div><div class="dashboard-hero__shape">+</div></div>
            <div class="dashboard-metrics"><Link :href="route('admin.patients.index')"><span class="dashboard-icon dashboard-icon--blue">P</span><div><small>Pacientes registrados</small><strong>{{ counts.patients }}</strong><i>Expedientes activos</i></div></Link><Link :href="route('admin.documents.index')"><span class="dashboard-icon dashboard-icon--aqua">D</span><div><small>Documentos hoy</small><strong>{{ counts.documents_today }}</strong><i>{{ counts.documents }} en historial</i></div></Link><Link :href="route('admin.documents.generate', 'constancia')"><span class="dashboard-icon dashboard-icon--green">C</span><div><small>Constancias</small><strong>{{ counts.certificates }}</strong><i>Emitidas y en proceso</i></div></Link><Link :href="route('admin.documents.generate', 'incapacidad')"><span class="dashboard-icon dashboard-icon--violet">I</span><div><small>Incapacidades</small><strong>{{ counts.incapacities }}</strong><i>Control documental</i></div></Link><Link class="metric-warning" :href="route('admin.documents.index', { status: 'REVIEW_REQUIRED' })"><span class="dashboard-icon dashboard-icon--orange">!</span><div><small>Pendientes de revisión</small><strong>{{ counts.pending_review }}</strong><i>Requieren atención</i></div></Link><Link :href="route('public.verify.lookup')"><span class="dashboard-icon dashboard-icon--dark">QR</span><div><small>Verificaciones QR</small><strong>{{ counts.verifications }}</strong><i>Consultas exitosas</i></div></Link></div>
            <div class="dashboard-main-grid"><div class="panel dashboard-activity"><div class="panel-head"><div><p class="kicker">Actividad reciente</p><h2>Últimos movimientos</h2></div><Link class="row-action" :href="route('admin.documents.index')">Ver historial →</Link></div><div v-if="recent.length" class="timeline-list"><Link v-for="document in recent" :key="document.id" class="timeline-item" :href="route('admin.documents.review', document.id)"><i></i><div><h3>{{ document.public_code || document.type.replaceAll('_', ' ') }}</h3><p>{{ document.patient ? `${document.patient.first_name} ${document.patient.last_name}` : 'Paciente por asignar' }}</p></div><div><StatusBadge :status="document.status" /><time>{{ date(document.created_at) }}</time></div></Link></div><div v-else class="activity-welcome"><span>✓</span><div><h3>El panel está listo para operar</h3><p>Los documentos que cargues o generes aparecerán aquí con su estado y trazabilidad.</p></div></div></div><aside class="panel quick-center"><div class="panel-head"><div><p class="kicker">Accesos rápidos</p><h2>¿Qué deseas hacer?</h2></div></div><Link :href="route('admin.documents.create')"><span>↑</span><div><strong>Cargar PDF existente</strong><small>Procesar y revisar un documento</small></div><b>→</b></Link><Link :href="route('admin.documents.generate', 'constancia')"><span>+</span><div><strong>Crear constancia</strong><small>Generar desde datos estructurados</small></div><b>→</b></Link><Link :href="route('admin.documents.generate', 'incapacidad')"><span>+</span><div><strong>Crear incapacidad</strong><small>Definir periodo y recomendaciones</small></div><b>→</b></Link><Link :href="route('admin.patients.index')"><span>⌕</span><div><strong>Buscar paciente</strong><small>Abrir expediente documental</small></div><b>→</b></Link></aside></div>
            <div class="network-summary"><div><small>RED CLÍNICA · BUILD {{ buildId }}</small><strong>{{ counts.active_clinics }} sedes activas</strong><span>{{ counts.doctors }} médicos · {{ counts.specialties }} especialidades</span></div><div class="network-summary__bar"><i v-for="index in 18" :key="index" :class="{ active: index <= counts.active_clinics }"></i></div><Link :href="route('public.clinics.index')">Ver red nacional →</Link></div>
        </section>
    </AdminLayout>
</template>
